
#include "ywdefs.h"
#include "ywos.h"
#include "ywlib.h"
#include "ywmid.h"
#include "ywgui_ext.h"
#include "res_layout.h"
#include "mcas_layout.h"


#define KEY_DLG_W 1060
#define KEY_DLG_H 530

#define KEY_DLG_CLIENT_W (KEY_DLG_W-20)
#define KEY_DLG_CLIENT_H (KEY_DLG_H-78)


#define  LZ_ADD_WINDOW
#ifdef LZ_ADD_WINDOW

static U16 g_aMcasColWidth[] =  {YWPUBLIC_COMM_DLG_W-100};

static YWGUI_LTShapeInfo_T *gstMcasCardDataShapeInfo[3] =
{
    &g_atColLTShapeInfo,
    NULL,
    NULL,
};
static const YWGUI_LTAddData_T g_tMcasCardData =
{
    1,
    9,
    g_aMcasColWidth,
    gstMcasCardDataShapeInfo,
    &g_tPosbarDef,
    0,
    NULL,
    NULL,
};


static YWGUI_CtrlTemplate_T g_ctrl_template_McasCardInfo[] =
{
    {(const S8*)YWGUI_CTRL_STATIC, YWGUI_WS_VISIBLE | YWGUI_SS_CENTER,YWGUI_WS_EX_TITLECTRL | YWGUI_WS_EX_TRANSPARENT,
        (YWPUBLIC_COMM_DLG_W - 400) / 2, 38, 400, 64, IDC_TTX_MCAS_CARDINFO_TITLE, STR_EMPTY, 0, 0},

    {(const S8*)YWGUI_CTRL_STATIC, YWGUI_WS_VISIBLE | YWGUI_SS_CENTER, YWGUI_WS_EX_TRANSPARENT,
        50 , 38, 1120, 64, IDC_TTX_MCAS_CARDINFO_SUBTITLE, STR_EMPTY, 0, &g_tListShapeInfo},

    /*listtable*/
    {(const S8*)YWGUI_CTRL_LISTTABLE, YWGUI_LTS_CENTER|YWGUI_WS_VISIBLE, YWGUI_LTS_CENTER|YWGUI_WS_EX_NONE,
        50, 150, 1120, 520,
        IDC_LT_MCAS_CARDINFO,
        STR_EMPTY,
        (DWORD)&g_tMcasCardData,
        &g_tListShapeInfo},

};


const YWGUI_DlgTemplate_T g_template_mcascardinfo =
{
    IDC_MCAS_CARDINFO,
    YWGUI_WS_VISIBLE |YWGUI_WS_BORDER,
    YWGUI_WS_EX_NONE/*|YWGUI_WS_EX_IRREGULAR*/|YWGUI_WS_EX_TRANSPARENT,
    (YWPUBLIC_OSD_W - YWPUBLIC_COMM_DLG_W)/2,
    (YWPUBLIC_OSD_H - YWPUBLIC_COMM_DLG_H)/2,
    YWPUBLIC_COMM_DLG_W,
    YWPUBLIC_COMM_DLG_H,
    0,
    YWGUI_ARRAY_SIZE(g_ctrl_template_McasCardInfo),
    g_ctrl_template_McasCardInfo,
    0,
    NULL
};


static YWGUI_CtrlTemplate_T g_ctrl_template_mcaskeyeditorentry[] =
{
    {(const S8*)YWGUI_CTRL_STATIC, YWGUI_WS_VISIBLE | YWGUI_SS_CENTER,YWGUI_WS_EX_TITLECTRL | YWGUI_WS_EX_TRANSPARENT,
        (YWPUBLIC_COMM_DLG_W - 400) / 2, 38, 400, 64, IDC_TTX_MCAS_KEYEDITOR_TITLE, STR_EMPTY, 0, 0},

    /*listtable*/
    {(const S8*)YWGUI_CTRL_LISTTABLE, YWGUI_LTS_CENTER|YWGUI_WS_VISIBLE, YWGUI_LTS_CENTER|YWGUI_WS_EX_NONE,
        50, 100, 1120, 520,
        IDC_LT_MCAS_KEYEDITOR,
        STR_EMPTY,
        (DWORD)&g_tMcasCardData,
        &g_tListShapeInfo},

};


const YWGUI_DlgTemplate_T g_template_mcaskeyeditorentry =
{
    IDC_MCAS_KEYEDITOR,
    YWGUI_WS_VISIBLE |YWGUI_WS_BORDER,
    YWGUI_WS_EX_NONE/*|YWGUI_WS_EX_IRREGULAR*/|YWGUI_WS_EX_TRANSPARENT,
    (YWPUBLIC_OSD_W - YWPUBLIC_COMM_DLG_W)/2,
    (YWPUBLIC_OSD_H - YWPUBLIC_COMM_DLG_H)/2,
	YWPUBLIC_COMM_DLG_W,
	YWPUBLIC_COMM_DLG_H,
	0,
	YWGUI_ARRAY_SIZE(g_ctrl_template_mcaskeyeditorentry),
	g_ctrl_template_mcaskeyeditorentry,
	0,
	NULL
};

#ifdef SLOT_2
#define SLOT_NUM  2
#else
#define SLOT_NUM  1
#endif

static YWGUI_CtrlTemplate_T g_ctrl_template_mcasmain[] =
{

    /*title text*/
    {(const S8*)YWGUI_CTRL_STATIC, YWGUI_WS_VISIBLE | YWGUI_SS_CENTER,YWGUI_WS_EX_TITLECTRL | YWGUI_WS_EX_TRANSPARENT,
        (YWPUBLIC_COMM_DLG_W - 400) / 2, 38, 400, 64, IDC_BTN_MCAS_MAIN_TITLE, STR_EMPTY, 0, 0},

    {(const S8*)YWGUI_CTRL_BUTTON, YWGUI_WS_VISIBLE|YWGUI_BS_CENTER|YWGUI_BS_VCENTER, YWGUI_WS_EX_NONE,
         100, 100+CTRL_COMMON_HIGH*0, 1020, CTRL_COMMON_HIGH,
         IDC_BTN_MCAS_MAIN_SLOTSTATUS,
         STR_EMPTY,
         0,
         &g_tButtonShapeInfo},

#ifdef SLOT_2
	{(const S8*)YWGUI_CTRL_BUTTON, YWGUI_WS_VISIBLE|YWGUI_BS_CENTER|YWGUI_BS_VCENTER, YWGUI_WS_EX_NONE,
         100, 100+CTRL_COMMON_HIGH*1, 1020, CTRL_COMMON_HIGH,
         IDC_BTN_MCAS_MAIN_SLOTSTATUS1,
         STR_EMPTY,
         0,
         &g_tButtonShapeInfo},
#endif
#ifdef MCAS_LITE

#else
    {(const S8*)YWGUI_CTRL_BUTTON, YWGUI_WS_VISIBLE|YWGUI_BS_CENTER|YWGUI_BS_VCENTER, YWGUI_WS_EX_NONE |YWGUI_WS_EX_NOTIFY,
         100, 100+CTRL_COMMON_HIGH*(SLOT_NUM), 1020, CTRL_COMMON_HIGH,
         IDC_BTN_MCAS_MAIN_KEYEDITOR,
         STR_EMPTY,
         0,
         &g_tButtonShapeInfo},

    {(const S8*)YWGUI_CTRL_BUTTON, YWGUI_WS_VISIBLE|YWGUI_BS_CENTER|YWGUI_BS_VCENTER, YWGUI_WS_EX_NONE |YWGUI_WS_EX_NOTIFY,
         100, 100+CTRL_COMMON_HIGH*(SLOT_NUM+1), 1020, CTRL_COMMON_HIGH,
         IDC_BTN_MCAS_MAIN_OPTION,
         STR_EMPTY,
         0,
         &g_tButtonShapeInfo},

    {(const S8*)YWGUI_CTRL_BUTTON, YWGUI_WS_VISIBLE|YWGUI_BS_CENTER|YWGUI_BS_VCENTER, YWGUI_WS_EX_NONE |YWGUI_WS_EX_NOTIFY,
         100, 100+CTRL_COMMON_HIGH*(SLOT_NUM+2), 1020, CTRL_COMMON_HIGH,
         IDC_BTN_MCAS_MAIN_INFORMATION,
         STR_EMPTY,
         0,
         &g_tButtonShapeInfo},

#endif

};

const YWGUI_DlgTemplate_T g_template_mcasmain =
{
    IDD_MCAS_MAIN,
    YWGUI_WS_VISIBLE |YWGUI_WS_BORDER,
    YWGUI_WS_EX_NONE/*|YWGUI_WS_EX_IRREGULAR*/|YWGUI_WS_EX_TRANSPARENT,
    (YWPUBLIC_OSD_W - YWPUBLIC_COMM_DLG_W)/2,
    (YWPUBLIC_OSD_H - YWPUBLIC_COMM_DLG_H)/2,
    YWPUBLIC_COMM_DLG_W,
    YWPUBLIC_COMM_DLG_H,
    0,
    YWGUI_ARRAY_SIZE(g_ctrl_template_mcasmain),
    g_ctrl_template_mcasmain,
    0,
    NULL
};



#endif

/*
static YWGUI_CtrlTemplate_T g_ctrl_template_pluginmain[] =
{

    {(const S8*)YWGUI_CTRL_BUTTON, YWGUI_WS_VISIBLE|YWGUI_BS_CENTER|YWGUI_BS_VCENTER, YWGUI_WS_EX_NONE,
         100, 100+CTRL_COMMON_HIGH*0, 1020, CTRL_COMMON_HIGH,
         IDC_BTN_PLUGIN_MAIN_MEDIAGUARD,
         STR_EMPTY,
         0,
         &g_tButtonShapeInfo},

    {(const S8*)YWGUI_CTRL_BUTTON, YWGUI_WS_VISIBLE|YWGUI_BS_CENTER|YWGUI_BS_VCENTER, YWGUI_WS_EX_NONE |YWGUI_WS_EX_NOTIFY,
         100, 100+CTRL_COMMON_HIGH*1, 1020, CTRL_COMMON_HIGH,
         IDC_BTN_PLUGIN_MAIN_VIACCESS,
         STR_EMPTY,
         0,
         &g_tButtonShapeInfo},

    {(const S8*)YWGUI_CTRL_BUTTON, YWGUI_WS_VISIBLE|YWGUI_BS_CENTER|YWGUI_BS_VCENTER, YWGUI_WS_EX_NONE |YWGUI_WS_EX_NOTIFY,
         100, 100+CTRL_COMMON_HIGH*2, 1020, CTRL_COMMON_HIGH,
         IDC_BTN_PLUGIN_MAIN_IRDETO,
         STR_EMPTY,
         0,
         &g_tButtonShapeInfo},

    {(const S8*)YWGUI_CTRL_BUTTON, YWGUI_WS_VISIBLE|YWGUI_BS_CENTER|YWGUI_BS_VCENTER, YWGUI_WS_EX_NONE |YWGUI_WS_EX_NOTIFY,
         100, 100+CTRL_COMMON_HIGH*3, 1020, CTRL_COMMON_HIGH,
         IDC_BTN_PLUGIN_MAIN_CRYPTOWORKS,
         STR_EMPTY,
         0,
         &g_tButtonShapeInfo},

    {(const S8*)YWGUI_CTRL_BUTTON, YWGUI_WS_VISIBLE|YWGUI_BS_CENTER|YWGUI_BS_VCENTER, YWGUI_WS_EX_NONE |YWGUI_WS_EX_NOTIFY,
         100, 100+CTRL_COMMON_HIGH*4, 1020, CTRL_COMMON_HIGH,
         IDC_BTN_PLUGIN_MAIN_NGRAVISION,
         STR_EMPTY,
         0,
         &g_tButtonShapeInfo},

    {(const S8*)YWGUI_CTRL_BUTTON, YWGUI_WS_VISIBLE|YWGUI_BS_CENTER|YWGUI_BS_VCENTER, YWGUI_WS_EX_NONE |YWGUI_WS_EX_NOTIFY,
         100, 100+CTRL_COMMON_HIGH*5, 1020, CTRL_COMMON_HIGH,
         IDC_BTN_PLUGIN_MAIN_VIDEOGUARD,
         STR_EMPTY,
         0,
         &g_tButtonShapeInfo},

    {(const S8*)YWGUI_CTRL_BUTTON, YWGUI_WS_VISIBLE|YWGUI_BS_CENTER|YWGUI_BS_VCENTER, YWGUI_WS_EX_NONE |YWGUI_WS_EX_NOTIFY,
         100, 100+CTRL_COMMON_HIGH*6, 1020, CTRL_COMMON_HIGH,
         IDC_BTN_PLUGIN_MAIN_CONAX,
         STR_EMPTY,
         0,
         &g_tButtonShapeInfo},
};

const YWGUI_DlgTemplate_T g_template_pluginmain =
{
    IDD_PLUGIN_MAIN,
    YWGUI_WS_VISIBLE |YWGUI_WS_BORDER,
    YWGUI_WS_EX_NONE|YWGUI_WS_EX_TRANSPARENT,
    (YWPUBLIC_OSD_W - YWPUBLIC_COMM_DLG_W)/2,
    (YWPUBLIC_OSD_H - YWPUBLIC_COMM_DLG_H)/2,
    YWPUBLIC_COMM_DLG_W,
    YWPUBLIC_COMM_DLG_H,
    0,
    YWGUI_ARRAY_SIZE(g_ctrl_template_pluginmain),
    g_ctrl_template_pluginmain,
    0,
    NULL
};
*/

#define _MCAS_OPTION_
#ifdef _MCAS_OPTION_

static YWGUI_LRCombobox_AddData_T McasDown2LRCBAddData =
{
    //Edit的外形
    &g_tLRCBEditShapeInfo,

    //List的位置
    0, 52, 510, (52*2+78),

    //List的外形
    &g_tPopDlgHaveHeadShapeInfo,
    &g_tLRCBListAddData
};


static YWGUI_CtrlTemplate_T g_ctrl_template_mcasoption[] =
{

    /*title text*/
    {(const S8*)YWGUI_CTRL_STATIC, YWGUI_WS_VISIBLE | YWGUI_SS_CENTER,YWGUI_WS_EX_TITLECTRL | YWGUI_WS_EX_TRANSPARENT,
        (YWPUBLIC_COMM_DLG_W - 400) / 2, 38, 400, 64, IDC_TXT_MCAS_OPTION_TITLE, STR_EMPTY, 0, 0},

	{(const S8*)YWGUI_CTRL_STATIC, YWGUI_WS_VISIBLE|YWGUI_SS_CENTER|YWGUI_SS_VCENTER, YWGUI_WS_EX_TRANSPARENT,
        100, 50, 300, CTRL_COMMON_HIGH,
        IDC_TXT_MCAS_OPTION, STR_EMPTY, 0, &g_tTxtBlackWhiteShapeInfo},

	{(const S8*)YWGUI_CTRL_LRCOMBOBOX, YWGUI_WS_VISIBLE|YWGUI_LRCBS_AUTOSCROLL|YWGUI_LRCBS_CENTER|YWGUI_LRCBS_VCENTER|YWGUI_LRCBS_EXITKEYHIDELIST,YWGUI_WS_EX_NOTIFY,
        (100+300), 50, 720, CTRL_COMMON_HIGH,
        IDC_LRC_MCAS_OPTION, 0, (DWORD)&McasDown2LRCBAddData, 0},

};

const YWGUI_DlgTemplate_T g_template_mcasoption =
{
    IDD_MCAS_OPTION,
    YWGUI_WS_VISIBLE |YWGUI_WS_BORDER,
    YWGUI_WS_EX_NONE/*|YWGUI_WS_EX_IRREGULAR*/|YWGUI_WS_EX_TRANSPARENT,
    (YWPUBLIC_OSD_W - YWPUBLIC_COMM_DLG_W)/2,
    (YWPUBLIC_OSD_H - YWPUBLIC_COMM_DLG_H)/2,
    YWPUBLIC_COMM_DLG_W,
    YWPUBLIC_COMM_DLG_H,
    0,
    YWGUI_ARRAY_SIZE(g_ctrl_template_mcasoption),
    g_ctrl_template_mcasoption,
    0,
    NULL
};


#endif

#define _SYS_INFO_
#ifdef _SYS_INFO_


static YWGUI_CtrlTemplate_T g_ctrl_template_mcassysinfo[] =
{
    /*title text*/
    {(const S8*)YWGUI_CTRL_STATIC, YWGUI_WS_VISIBLE | YWGUI_SS_CENTER,YWGUI_WS_EX_TITLECTRL | YWGUI_WS_EX_TRANSPARENT,
        (YWPUBLIC_COMM_DLG_W - 400) / 2, 38, 400, 64, IDC_TXT_MCAS_SYSINFO_TITLE, STR_EMPTY, 0, 0},

	{(const S8*)YWGUI_CTRL_STATIC, YWGUI_WS_VISIBLE|YWGUI_SS_LEFT|YWGUI_SS_VCENTER, YWGUI_WS_EX_TRANSPARENT,
        100, 50, 510, CTRL_COMMON_HIGH,
        IDC_TXT_MCAS_SYSINFO_VERSION_L, STR_EMPTY, 0, &g_tTxtBlackGrayBlueShapeInfo},

	{(const S8*)YWGUI_CTRL_STATIC, YWGUI_WS_VISIBLE|YWGUI_SS_CENTER|YWGUI_SS_VCENTER, YWGUI_WS_EX_TRANSPARENT,
        100+510, 50, 510, CTRL_COMMON_HIGH,
        IDC_TXT_MCAS_SYSINFO_VERSION_R, STR_EMPTY, 0, &g_tTxtBlackGrayBlueShapeInfo},

	{(const S8*)YWGUI_CTRL_STATIC, YWGUI_WS_VISIBLE|YWGUI_SS_LEFT|YWGUI_SS_VCENTER, YWGUI_WS_EX_TRANSPARENT,
        100, 50+CTRL_COMMON_HIGH, 510, CTRL_COMMON_HIGH,
        IDC_TXT_MCAS_SYSINFO_COMPILEDT_L, STR_EMPTY, 0, &g_tTxtBlackGrayBlueShapeInfo},

	{(const S8*)YWGUI_CTRL_STATIC, YWGUI_WS_VISIBLE|YWGUI_SS_CENTER|YWGUI_SS_VCENTER, YWGUI_WS_EX_TRANSPARENT,
        100+510, 50+CTRL_COMMON_HIGH, 510, CTRL_COMMON_HIGH,
        IDC_TXT_MCAS_SYSINFO_COMPILEDT_R, STR_EMPTY, 0, &g_tTxtBlackGrayBlueShapeInfo},

	{(const S8*)YWGUI_CTRL_STATIC, YWGUI_WS_VISIBLE|YWGUI_SS_LEFT|YWGUI_SS_VCENTER, YWGUI_WS_EX_TRANSPARENT,
        100, 50+CTRL_COMMON_HIGH*2, 510, CTRL_COMMON_HIGH,
        IDC_TXT_MCAS_SYSINFO_VISITUS_L, STR_EMPTY, 0, &g_tTxtBlackGrayBlueShapeInfo},

	{(const S8*)YWGUI_CTRL_STATIC, YWGUI_WS_VISIBLE|YWGUI_SS_CENTER|YWGUI_SS_VCENTER, YWGUI_WS_EX_TRANSPARENT,
        100+510, 50+CTRL_COMMON_HIGH*2, 510, CTRL_COMMON_HIGH,
        IDC_TXT_MCAS_SYSINFO_VISITUS_R, STR_EMPTY, 0, &g_tTxtBlackGrayBlueShapeInfo},
	{(const S8*)YWGUI_CTRL_STATIC, YWGUI_WS_VISIBLE|YWGUI_SS_CENTER|YWGUI_SS_VCENTER, YWGUI_WS_EX_TRANSPARENT,
        100+510, 50+CTRL_COMMON_HIGH*3, 510, CTRL_COMMON_HIGH,
        IDC_TXT_MCAS_SYSINFO_VISITUS_R1, STR_EMPTY, 0, &g_tTxtBlackGrayBlueShapeInfo},
	{(const S8*)YWGUI_CTRL_STATIC, YWGUI_WS_VISIBLE|YWGUI_SS_CENTER|YWGUI_SS_VCENTER, YWGUI_WS_EX_TRANSPARENT,
        100+510, 50+CTRL_COMMON_HIGH*4, 510, CTRL_COMMON_HIGH,
        IDC_TXT_MCAS_SYSINFO_VISITUS_R2, STR_EMPTY, 0, &g_tTxtBlackGrayBlueShapeInfo},
	{(const S8*)YWGUI_CTRL_STATIC, YWGUI_WS_VISIBLE|YWGUI_SS_CENTER|YWGUI_SS_VCENTER, YWGUI_WS_EX_TRANSPARENT,
        100+510, 50+CTRL_COMMON_HIGH*5, 510, CTRL_COMMON_HIGH,
        IDC_TXT_MCAS_SYSINFO_VISITUS_R3, STR_EMPTY, 0, &g_tTxtBlackGrayBlueShapeInfo},

};

const YWGUI_DlgTemplate_T g_template_mcassysinfo =
{
    IDD_MCAS_SYSINFO,
    YWGUI_WS_VISIBLE |YWGUI_WS_BORDER,
    YWGUI_WS_EX_NONE/*|YWGUI_WS_EX_IRREGULAR*/|YWGUI_WS_EX_TRANSPARENT,
    (YWPUBLIC_OSD_W - YWPUBLIC_COMM_DLG_W)/2,
    (YWPUBLIC_OSD_H - YWPUBLIC_COMM_DLG_H)/2,
    YWPUBLIC_COMM_DLG_W,
    YWPUBLIC_COMM_DLG_H,
    0,
    YWGUI_ARRAY_SIZE(g_ctrl_template_mcassysinfo),
    g_ctrl_template_mcassysinfo,
    0,
    NULL
};

#endif


#define _KEY_INFO_
#ifdef _KEY_INFO_

static U16 g_aColWidth[] =  {100,150,150,150,150, 400};
static YWGUI_LTShapeInfo_T *gstKeyInfoLTShapeInfo[3] =
{
    &g_atColLTShapeInfo,
    NULL,
    NULL,
};
static const YWGUI_LTAddData_T g_tKeyInfoLTAddData =
{
    6,
    10,
    g_aColWidth,
    gstKeyInfoLTShapeInfo,
    &g_tPosbarDef,
    0,
    NULL,
    NULL,
};

static YWGUI_CtrlTemplate_T g_ctrl_template_pluginkeyinfo[] =
{
    {(const S8*)YWGUI_CTRL_STATIC, YWGUI_WS_VISIBLE | YWGUI_SS_CENTER, YWGUI_WS_EX_TITLECTRL|YWGUI_WS_EX_TRANSPARENT,
        (YWPUBLIC_COMM_DLG_W - 400) / 2, 38, 400, 64, IDC_TTX_PLUGIN_KEY_INFO_TITLE, STR_EMPTY, 0, 0},


	//list table title
	{(const S8*)YWGUI_CTRL_STATIC, YWGUI_WS_VISIBLE|YWGUI_SS_LEFT|YWGUI_SS_VCENTER, YWGUI_WS_EX_NONE,
        50, 10, 110, CTRL_COMMON_HIGH,
        IDC_TXT_PLUGIN_KEY_INFO_NO,
        STR_EMPTY,
        0,
        &g_tTxtBlueBlackShapeInfo},
	{(const S8*)YWGUI_CTRL_STATIC, YWGUI_WS_VISIBLE|YWGUI_SS_LEFT|YWGUI_SS_VCENTER, YWGUI_WS_EX_NONE,
        150+10, 10, 150, CTRL_COMMON_HIGH,
        IDC_TXT_PLUGIN_KEY_INFO_CAID,
        STR_EMPTY,
        0,
        &g_tTxtBlueBlackShapeInfo},
	{(const S8*)YWGUI_CTRL_STATIC, YWGUI_WS_VISIBLE|YWGUI_SS_LEFT|YWGUI_SS_VCENTER, YWGUI_WS_EX_NONE,
        300+10, 10, 150, CTRL_COMMON_HIGH,
        IDC_TXT_PLUGIN_KEY_INFO_PROVIDER,
        STR_EMPTY,
        0,
        &g_tTxtBlueBlackShapeInfo},
	{(const S8*)YWGUI_CTRL_STATIC, YWGUI_WS_VISIBLE|YWGUI_SS_LEFT|YWGUI_SS_VCENTER, YWGUI_WS_EX_NONE,
        450+10, 10, 150, CTRL_COMMON_HIGH,
        IDC_TXT_PLUGIN_KEY_INFO_TYPE,
        STR_EMPTY,
        0,
        &g_tTxtBlueBlackShapeInfo},
	{(const S8*)YWGUI_CTRL_STATIC, YWGUI_WS_VISIBLE|YWGUI_SS_LEFT|YWGUI_SS_VCENTER, YWGUI_WS_EX_NONE,
        600+10, 10, 160, CTRL_COMMON_HIGH,
        IDC_TXT_PLUGIN_KEY_INFO_INDEX,
        STR_EMPTY,
        0,
        &g_tTxtBlueBlackShapeInfo},

	{(const S8*)YWGUI_CTRL_STATIC, YWGUI_WS_VISIBLE|YWGUI_SS_LEFT|YWGUI_SS_VCENTER, YWGUI_WS_EX_NONE,
        770, 10, 400, CTRL_COMMON_HIGH,
        IDC_TXT_PLUGIN_KEY_INFO_KEY_DATA,
        STR_EMPTY,
        0,
        &g_tTxtBlueBlackShapeInfo},

    /*listtable*/
    {(const S8*)YWGUI_CTRL_LISTTABLE, YWGUI_WS_VISIBLE, YWGUI_WS_EX_NONE,
        50, 70, 1120, 520,
        IDC_LT_PLUGIN_KEY_INFO,
        STR_EMPTY,
        (DWORD)&g_tKeyInfoLTAddData,
        &g_tListShapeInfo},


	/*function ctrl*/
    {(const S8*)YWGUI_CTRL_PICTURE,YWGUI_WS_VISIBLE,YWGUI_WS_EX_NONE,
       HOTKEY_START_X, HOTKEY_START_Y,46,46,
       IDC_PIC_PLUGIN_KEY_INFO_EDIT,
       STR_EMPTY,
       (DWORD)&g_aGraphCellArray[YWCELL_RED],
       0},
    {(const S8*)YWGUI_CTRL_STATIC, YWGUI_WS_VISIBLE|YWGUI_SS_VCENTER|YWGUI_SS_LEFT, YWGUI_WS_EX_TRANSPARENT,
        HOTKEY_START_X+50, HOTKEY_START_Y, 150, CTRL_COMMON_HIGH,
        IDC_TXT_PLUGIN_KEY_INFO_EDIT,
        STR_EMPTY,
        0,
        &g_tTxtBlackWhiteShapeInfo},


    {(const S8*)YWGUI_CTRL_PICTURE,YWGUI_WS_VISIBLE,YWGUI_WS_EX_TRANSPARENT,
       HOTKEY_START_X+200, HOTKEY_START_Y,46,46,
       IDC_PIC_PLUGIN_KEY_INFO_ADD,
       STR_EMPTY,
       (DWORD)&g_aGraphCellArray[YWCELL_GREEN],
       0},

    {(const S8*)YWGUI_CTRL_STATIC, YWGUI_WS_VISIBLE|YWGUI_SS_VCENTER|YWGUI_SS_LEFT, YWGUI_WS_EX_TRANSPARENT,
        HOTKEY_START_X+250, HOTKEY_START_Y, 150, CTRL_COMMON_HIGH,
        IDC_TXT_PLUGIN_KEY_INFO_ADD,
        STR_EMPTY,
        0,
        &g_tTxtBlackWhiteShapeInfo},

    {(const S8*)YWGUI_CTRL_PICTURE,YWGUI_WS_VISIBLE,YWGUI_WS_EX_TRANSPARENT,
       HOTKEY_START_X+400, HOTKEY_START_Y,46,46,
       IDC_PIC_PLUGIN_KEY_INFO_DELETE,
       STR_EMPTY,
       (DWORD)&g_aGraphCellArray[YWCELL_YELLOW],
       0},
    {(const S8*)YWGUI_CTRL_STATIC, YWGUI_WS_VISIBLE|YWGUI_SS_VCENTER|YWGUI_SS_LEFT, YWGUI_WS_EX_TRANSPARENT,
        HOTKEY_START_X+450, HOTKEY_START_Y, 150, CTRL_COMMON_HIGH,
        IDC_TXT_PLUGIN_KEY_INFO_DELETE,
        STR_EMPTY,
        0,
        &g_tTxtBlackWhiteShapeInfo},

    {(const S8*)YWGUI_CTRL_PICTURE,YWGUI_WS_VISIBLE,YWGUI_WS_EX_TRANSPARENT,
       HOTKEY_START_X+600, HOTKEY_START_Y,46,46,
       IDC_PIC_PLUGIN_KEY_INFO_RESET,
       STR_EMPTY,
       (DWORD)&g_aGraphCellArray[YWCELL_BLUE],
       0},
    {(const S8*)YWGUI_CTRL_STATIC, YWGUI_WS_VISIBLE|YWGUI_SS_VCENTER|YWGUI_SS_LEFT, YWGUI_WS_EX_TRANSPARENT,
        HOTKEY_START_X+650, HOTKEY_START_Y, 150, CTRL_COMMON_HIGH,
        IDC_TXT_PLUGIN_KEY_INFO_RESET,
        STR_EMPTY,
        0,
        &g_tTxtBlackWhiteShapeInfo},
};

const YWGUI_DlgTemplate_T g_template_pluginkeyinfo =
{
    IDD_PLUGIN_KEY_INFO,
    YWGUI_WS_VISIBLE,
    YWGUI_WS_EX_NONE/*|YWGUI_WS_EX_IRREGULAR*/|YWGUI_WS_EX_TRANSPARENT,
    (YWPUBLIC_OSD_W - YWPUBLIC_COMM_DLG_W)/2,
    (YWPUBLIC_OSD_H - YWPUBLIC_COMM_DLG_H)/2,
	YWPUBLIC_COMM_DLG_W,
	YWPUBLIC_COMM_DLG_H,
    -1,
    YWGUI_ARRAY_SIZE(g_ctrl_template_pluginkeyinfo),
    g_ctrl_template_pluginkeyinfo,
    0,
    NULL
};

#endif

#define _KEY_EDIT_WND
#ifdef _KEY_EDIT_WND

static YWGUI_CtrlTemplate_T g_ctrl_template_pluginkeyedit[] =
{
	//Edit dlg tile
	{(const S8*)YWGUI_CTRL_STATIC, YWGUI_WS_VISIBLE|YWGUI_SS_CENTER|YWGUI_SS_VCENTER, YWGUI_WS_EX_TITLECTRL|YWGUI_WS_EX_TRANSPARENT,
        (KEY_DLG_W-400)/2, 0, 400, 64,
        IDC_TXT_PLUGIN_KEY_EDIT_TITLE, STR_EMPTY, 0,0},

	//list table title
	{(const S8*)YWGUI_CTRL_STATIC, YWGUI_WS_VISIBLE|YWGUI_SS_CENTER|YWGUI_SS_VCENTER, YWGUI_WS_EX_NONE,
        0, 10, 100, CTRL_COMMON_HIGH, IDC_TXT_PLUGIN_KEY_EDIT_CAID,
        STR_EMPTY,
        0,
        &g_tTxtGrayBlueFrameBlackShapeInfo},
	{(const S8*)YWGUI_CTRL_STATIC, YWGUI_WS_VISIBLE|YWGUI_SS_CENTER|YWGUI_SS_VCENTER, YWGUI_WS_EX_NONE,
        100, 10, 150, CTRL_COMMON_HIGH, IDC_TXT_PLUGIN_KEY_EDIT_PROVIDER,
        STR_EMPTY,
        0,
        &g_tTxtGrayBlueFrameBlackShapeInfo},
	{(const S8*)YWGUI_CTRL_STATIC, YWGUI_WS_VISIBLE|YWGUI_SS_CENTER|YWGUI_SS_VCENTER, YWGUI_WS_EX_NONE,
        250, 10, 150, CTRL_COMMON_HIGH, IDC_TXT_PLUGIN_KEY_EDIT_TYPE,
        STR_EMPTY,
        0,
        &g_tTxtGrayBlueFrameBlackShapeInfo},
	{(const S8*)YWGUI_CTRL_STATIC, YWGUI_WS_VISIBLE|YWGUI_SS_CENTER|YWGUI_SS_VCENTER, YWGUI_WS_EX_NONE,
        400, 10, 150, CTRL_COMMON_HIGH, IDC_TXT_PLUGIN_KEY_EDIT_INDEX,
        STR_EMPTY,
        0,
        &g_tTxtGrayBlueFrameBlackShapeInfo},
	{(const S8*)YWGUI_CTRL_STATIC, YWGUI_WS_VISIBLE|YWGUI_SS_CENTER|YWGUI_SS_VCENTER, YWGUI_WS_EX_NONE,
        550, 10, 490, CTRL_COMMON_HIGH, IDC_TXT_PLUGIN_KEY_EDIT_KEY_DATA,
        STR_EMPTY,
        0,
        &g_tTxtGrayBlueFrameBlackShapeInfo},

	//key content
	{(const S8*)YWGUI_CTRL_STATIC, YWGUI_WS_VISIBLE|YWGUI_SS_CENTER|YWGUI_SS_VCENTER, YWGUI_WS_EX_TRANSPARENT,
        0, CTRL_COMMON_HIGH+10*2, 100, CTRL_COMMON_HIGH, IDC_TXT_PLUGIN_KEY_EDIT_CAID_CONTENT,
        STR_EMPTY,
        0,
        &g_tTxtOrangeBlackShapeInfo},
	{(const S8*)YWGUI_CTRL_STATIC, YWGUI_WS_VISIBLE|YWGUI_SS_CENTER|YWGUI_SS_VCENTER, YWGUI_WS_EX_TRANSPARENT,
        100, CTRL_COMMON_HIGH+10*2, 150, CTRL_COMMON_HIGH, IDC_TXT_PLUGIN_KEY_EDIT_PROVIDER_CONTENT,
        STR_EMPTY,
        0,
        &g_tTxtOrangeBlackShapeInfo},
	{(const S8*)YWGUI_CTRL_STATIC, YWGUI_WS_VISIBLE|YWGUI_SS_CENTER|YWGUI_SS_VCENTER, YWGUI_WS_EX_TRANSPARENT,
        250, CTRL_COMMON_HIGH+10*2, 150, CTRL_COMMON_HIGH, IDC_TXT_PLUGIN_KEY_EDIT_TYPE_CONTENT,
        STR_EMPTY,
        0,
        &g_tTxtOrangeBlackShapeInfo},
	{(const S8*)YWGUI_CTRL_STATIC, YWGUI_WS_VISIBLE|YWGUI_SS_CENTER|YWGUI_SS_VCENTER, YWGUI_WS_EX_TRANSPARENT,
        400, CTRL_COMMON_HIGH+10*2, 150, CTRL_COMMON_HIGH, IDC_TXT_PLUGIN_KEY_EDIT_INDEX_CONTENT,
        STR_EMPTY,
        0,
        &g_tTxtOrangeBlackShapeInfo},
    {(const S8*)YWGUI_CTRL_SEDIT, YWGUI_WS_VISIBLE|YWGUI_ES_CENTER|YWGUI_ES_VCENTER|YWGUI_ES_REPLACE,YWGUI_WS_EX_NOTIFY,
        550, CTRL_COMMON_HIGH+10*2, 490, CTRL_COMMON_HIGH,IDC_EDIT_PLUGIN_KEY_EDIT_KEY_DATA_CONTENT,
        STR_EMPTY,
        0,
        &g_tEditShapeInfo},

	/*function ctrl*/
    {(const S8*)YWGUI_CTRL_STATIC, YWGUI_WS_VISIBLE|YWGUI_SS_VCENTER|YWGUI_SS_LEFT, YWGUI_WS_EX_TRANSPARENT,
        10, KEY_DLG_CLIENT_H-CTRL_COMMON_HIGH*2, 600, CTRL_COMMON_HIGH,
        IDC_TXT_PLUGIN_KEY_EDIT_HELP_INFO1,
        STR_EMPTY,
        0,
        &g_tTxtBlackWhiteShapeInfo},
    {(const S8*)YWGUI_CTRL_STATIC, YWGUI_WS_VISIBLE|YWGUI_SS_VCENTER|YWGUI_SS_LEFT, YWGUI_WS_EX_TRANSPARENT,
        10, KEY_DLG_CLIENT_H-CTRL_COMMON_HIGH, 600, CTRL_COMMON_HIGH,
        IDC_TXT_PLUGIN_KEY_EDIT_HELP_INFO2,
        STR_EMPTY,
        0,
        &g_tTxtBlackWhiteShapeInfo},
};

const YWGUI_DlgTemplate_T g_template_pluginkeyedit =
{
    IDD_PLUGIN_KEY_EDIT,
    YWGUI_WS_VISIBLE,
    YWGUI_WS_EX_NONE,
    (YWPUBLIC_OSD_W - KEY_DLG_W)/2,
    (YWPUBLIC_OSD_H - KEY_DLG_H)/2,
	KEY_DLG_W,
	KEY_DLG_H,
    -1,
    YWGUI_ARRAY_SIZE(g_ctrl_template_pluginkeyedit),
    g_ctrl_template_pluginkeyedit,
    0,
    NULL
};
#endif

#define _KEY_EDIT_ADD
#ifdef _KEY_EDIT_ADD

YWGUI_ShapeInfo_T g_tKeyAddEditShapeInfo =
{
    {
        &g_tEditShapeState_AFocus,//YWGUI_STATUS_NORMAL
        &g_tEditShapeState_Disable,//YWGUI_STATUS_DISABLED
        &g_tEditShapeState_AFocus,//YWGUI_STATUS_AFOCUS
        &g_tEditShapeState_AFocus//NULL,//YWGUI_STATUS_SFOCUS

    }
};

YWGUI_ShapeInfo_T g_tKeyTypeEditShapeInfo =
{
    {
        &g_tEditShapeState_AFocus,//YWGUI_STATUS_NORMAL
        &g_tEditShapeState_Disable,//YWGUI_STATUS_DISABLED
        &g_tEditShapeState_AFocus_EX,//YWGUI_STATUS_AFOCUS
        &g_tEditShapeState_AFocus_EX//NULL,//YWGUI_STATUS_SFOCUS

    }
};
static YWGUI_CtrlTemplate_T g_ctrl_template_pluginkeyadd[] =
{
	//add title
	{(const S8*)YWGUI_CTRL_STATIC, YWGUI_WS_VISIBLE|YWGUI_SS_CENTER|YWGUI_SS_VCENTER, YWGUI_WS_EX_TITLECTRL|YWGUI_WS_EX_TRANSPARENT,
        (KEY_DLG_W-400)/2, 0, 400, 64,
        IDC_TXT_PLUGIN_KEY_ADD_TITLE, STR_EMPTY, 0,0},


	//list table title
	{(const S8*)YWGUI_CTRL_STATIC, YWGUI_WS_VISIBLE|YWGUI_SS_CENTER|YWGUI_SS_VCENTER, YWGUI_WS_EX_TRANSPARENT,
        0, 10, 100, CTRL_COMMON_HIGH,
        IDC_TXT_PLUGIN_KEY_ADD_CAID,
        STR_EMPTY,
        0,
        &g_tTxtBlueBlackShapeInfo},
	{(const S8*)YWGUI_CTRL_STATIC, YWGUI_WS_VISIBLE|YWGUI_SS_CENTER|YWGUI_SS_VCENTER, YWGUI_WS_EX_TRANSPARENT,
        100, 10, 150, CTRL_COMMON_HIGH,
        IDC_TXT_PLUGIN_KEY_ADD_PROVIDER,
        STR_EMPTY,
        0,
        &g_tTxtBlueBlackShapeInfo},
	{(const S8*)YWGUI_CTRL_STATIC, YWGUI_WS_VISIBLE|YWGUI_SS_CENTER|YWGUI_SS_VCENTER, YWGUI_WS_EX_TRANSPARENT,
        250, 10, 150, CTRL_COMMON_HIGH,
        IDC_TXT_PLUGIN_KEY_ADD_TYPE,
        STR_EMPTY,
        0,
        &g_tTxtBlueBlackShapeInfo},
	{(const S8*)YWGUI_CTRL_STATIC, YWGUI_WS_VISIBLE|YWGUI_SS_CENTER|YWGUI_SS_VCENTER, YWGUI_WS_EX_TRANSPARENT,
        400, 10, 150, CTRL_COMMON_HIGH,
        IDC_TXT_PLUGIN_KEY_ADD_INDEX,
        STR_EMPTY,
        0,
        &g_tTxtBlueBlackShapeInfo},
	{(const S8*)YWGUI_CTRL_STATIC, YWGUI_WS_VISIBLE|YWGUI_SS_CENTER|YWGUI_SS_VCENTER, YWGUI_WS_EX_TRANSPARENT,
        550, 10, 490, CTRL_COMMON_HIGH,
        IDC_TXT_PLUGIN_KEY_ADD_KEY_DATA,
        STR_EMPTY,
        0,
        &g_tTxtBlueBlackShapeInfo},

	//content
    {(const S8*)YWGUI_CTRL_SEDIT, YWGUI_WS_VISIBLE|YWGUI_SS_CENTER|YWGUI_ES_VCENTER|YWGUI_ES_REPLACE,YWGUI_WS_EX_NOTIFY,
        0, CTRL_COMMON_HIGH+10*2, 100, CTRL_COMMON_HIGH,
        IDC_EDIT_PLUGIN_KEY_ADD_CAID_CONTENT,
        STR_EMPTY,
        0,
        &g_tKeyAddEditShapeInfo},

    {(const S8*)YWGUI_CTRL_SEDIT, YWGUI_WS_VISIBLE|YWGUI_SS_CENTER|YWGUI_ES_VCENTER|YWGUI_ES_REPLACE,YWGUI_WS_EX_NOTIFY,
        100, CTRL_COMMON_HIGH+10*2, 150, CTRL_COMMON_HIGH,
        IDC_EDIT_PLUGIN_KEY_ADD_PROVIDER_CONTENT,
        STR_EMPTY,
        0,
        &g_tKeyAddEditShapeInfo},

    {(const S8*)YWGUI_CTRL_BUTTON, YWGUI_WS_VISIBLE|YWGUI_SS_CENTER|YWGUI_BS_VCENTER, YWGUI_WS_EX_NONE |YWGUI_WS_EX_NOTIFY,
        250, CTRL_COMMON_HIGH+10*2, 150, CTRL_COMMON_HIGH,
        IDC_BTN_PLUGIN_KEY_ADD_TYPE_CONTENT,
        STR_EMPTY,
        0,
        &g_tKeyTypeEditShapeInfo},

    {(const S8*)YWGUI_CTRL_SEDIT, YWGUI_WS_VISIBLE|YWGUI_ES_CENTER|YWGUI_ES_VCENTER|YWGUI_ES_REPLACE,YWGUI_WS_EX_NOTIFY,
        400, CTRL_COMMON_HIGH+10*2, 150, CTRL_COMMON_HIGH,
        IDC_EDIT_PLUGIN_KEY_ADD_INDEX_CONTENT,
        STR_EMPTY,
        0,
        &g_tKeyAddEditShapeInfo},

    {(const S8*)YWGUI_CTRL_SEDIT, YWGUI_WS_VISIBLE|YWGUI_ES_CENTER|YWGUI_ES_VCENTER|YWGUI_ES_REPLACE,YWGUI_WS_EX_NOTIFY,
        550, CTRL_COMMON_HIGH+10*2, 490, CTRL_COMMON_HIGH,
        IDC_EDIT_PLUGIN_KEY_ADD_KEY_DATA_CONTENT,
        STR_EMPTY,
        0,
        &g_tKeyAddEditShapeInfo},

    /*{(const S8*)YWGUI_CTRL_SEDIT, YWGUI_WS_VISIBLE|YWGUI_ES_CENTER|YWGUI_ES_VCENTER|YWGUI_ES_REPLACE,YWGUI_WS_EX_NOTIFY,
        550, 114 + CTRL_COMMON_HIGH + 10, 510, CTRL_COMMON_HIGH,
        IDC_EDIT_PLUGIN_KEY_ADD_KEY_DATA_CONTENT1,
        STR_EMPTY,
        0,
        &g_tKeyAddEditShapeInfo},*/

	/*function ctrl*/
    {(const S8*)YWGUI_CTRL_STATIC, YWGUI_WS_VISIBLE|YWGUI_SS_VCENTER|YWGUI_SS_LEFT, YWGUI_WS_EX_TRANSPARENT,
        10, KEY_DLG_CLIENT_H-CTRL_COMMON_HIGH*2, 600, CTRL_COMMON_HIGH,
        IDC_TXT_PLUGIN_KEY_ADD_HELP_INFO1,
        STR_EMPTY,
        0,
        &g_tTxtBlackWhiteShapeInfo},
    {(const S8*)YWGUI_CTRL_STATIC, YWGUI_WS_VISIBLE|YWGUI_SS_VCENTER|YWGUI_SS_LEFT, YWGUI_WS_EX_TRANSPARENT,
        10, KEY_DLG_CLIENT_H-CTRL_COMMON_HIGH, 600, CTRL_COMMON_HIGH,
        IDC_TXT_PLUGIN_KEY_ADD_HELP_INFO2,
        STR_EMPTY,
        0,
        &g_tTxtBlackWhiteShapeInfo},
};

const YWGUI_DlgTemplate_T g_template_pluginkeyadd =
{
    IDD_PLUGIN_KEY_ADD,
    YWGUI_WS_VISIBLE,
    YWGUI_WS_EX_NONE,
    (YWPUBLIC_OSD_W - KEY_DLG_W)/2,
    (YWPUBLIC_OSD_H - KEY_DLG_H)/2,
	KEY_DLG_W,
	KEY_DLG_H,
    -1,
    YWGUI_ARRAY_SIZE(g_ctrl_template_pluginkeyadd),
    g_ctrl_template_pluginkeyadd,
    0,
    NULL
};
#endif


