
#ifndef _MCAS_LAYOUT_H
#define _MCAS_LAYOUT_H

/*the ID of window*/
typedef enum
{

#ifdef LZ_ADD_WINDOW
    IDD_MCAS_MAIN = 0x300,
    IDC_BTN_MCAS_MAIN_TITLE,
    IDC_BTN_MCAS_MAIN_SLOTSTATUS,
#ifdef SLOT_2    
    IDC_BTN_MCAS_MAIN_SLOTSTATUS1,
#endif    
    IDC_BTN_MCAS_MAIN_KEYEDITOR,
    IDC_BTN_MCAS_MAIN_OPTION,
    IDC_BTN_MCAS_MAIN_INFORMATION,

    IDC_MCAS_CARDINFO,
    IDC_TTX_MCAS_CARDINFO_TITLE,
    IDC_TTX_MCAS_CARDINFO_SUBTITLE,
    IDC_LT_MCAS_CARDINFO,

    IDC_MCAS_KEYEDITOR,
    IDC_TTX_MCAS_KEYEDITOR_TITLE,
    IDC_LT_MCAS_KEYEDITOR,

#endif
    IDD_MCAS_OPTION,
    IDC_TXT_MCAS_OPTION_TITLE,
    IDC_TXT_MCAS_OPTION,
    IDC_LRC_MCAS_OPTION,

    IDD_MCAS_SYSINFO,
    IDC_TXT_MCAS_SYSINFO_TITLE,
    IDC_TXT_MCAS_SYSINFO_VERSION_L,
    IDC_TXT_MCAS_SYSINFO_VERSION_R,
    IDC_TXT_MCAS_SYSINFO_COMPILEDT_L,
    IDC_TXT_MCAS_SYSINFO_COMPILEDT_R,
    IDC_TXT_MCAS_SYSINFO_VISITUS_L,
    IDC_TXT_MCAS_SYSINFO_VISITUS_R,
    IDC_TXT_MCAS_SYSINFO_VISITUS_R1,
    IDC_TXT_MCAS_SYSINFO_VISITUS_R2,
    IDC_TXT_MCAS_SYSINFO_VISITUS_R3,

    IDD_PLUGIN_MAIN,
    IDC_BTN_PLUGIN_MAIN_MEDIAGUARD,
    IDC_BTN_PLUGIN_MAIN_VIACCESS,
    IDC_BTN_PLUGIN_MAIN_IRDETO,
    IDC_BTN_PLUGIN_MAIN_CRYPTOWORKS,
    IDC_BTN_PLUGIN_MAIN_NGRAVISION,
    IDC_BTN_PLUGIN_MAIN_VIDEOGUARD,
    IDC_BTN_PLUGIN_MAIN_CONAX,

    IDD_PLUGIN_KEY_INFO,
    IDC_TTX_PLUGIN_KEY_INFO_TITLE,
	IDC_TXT_PLUGIN_KEY_INFO_NO,
	IDC_TXT_PLUGIN_KEY_INFO_CAID,
	IDC_TXT_PLUGIN_KEY_INFO_PROVIDER,
	IDC_TXT_PLUGIN_KEY_INFO_TYPE,
	IDC_TXT_PLUGIN_KEY_INFO_INDEX,
	IDC_TXT_PLUGIN_KEY_INFO_KEY_DATA,
	IDC_LT_PLUGIN_KEY_INFO,

	IDC_TXT_PLUGIN_KEY_INFO_EDIT,
	IDC_TXT_PLUGIN_KEY_INFO_ADD,
	IDC_TXT_PLUGIN_KEY_INFO_DELETE,
	IDC_TXT_PLUGIN_KEY_INFO_RESET,
	IDC_PIC_PLUGIN_KEY_INFO_EDIT,
	IDC_PIC_PLUGIN_KEY_INFO_ADD,
	IDC_PIC_PLUGIN_KEY_INFO_DELETE,
	IDC_PIC_PLUGIN_KEY_INFO_RESET,


    IDD_PLUGIN_KEY_EDIT,
	IDC_TXT_PLUGIN_KEY_EDIT_TITLE,
	IDC_TXT_PLUGIN_KEY_EDIT_CAID,
	IDC_TXT_PLUGIN_KEY_EDIT_PROVIDER,
	IDC_TXT_PLUGIN_KEY_EDIT_TYPE,
	IDC_TXT_PLUGIN_KEY_EDIT_INDEX,
	IDC_TXT_PLUGIN_KEY_EDIT_KEY_DATA,
	IDC_TXT_PLUGIN_KEY_EDIT_CAID_CONTENT,
	IDC_TXT_PLUGIN_KEY_EDIT_PROVIDER_CONTENT,
	IDC_TXT_PLUGIN_KEY_EDIT_TYPE_CONTENT,
	IDC_TXT_PLUGIN_KEY_EDIT_INDEX_CONTENT,
	IDC_EDIT_PLUGIN_KEY_EDIT_KEY_DATA_CONTENT,
	IDC_TXT_PLUGIN_KEY_EDIT_HELP_INFO1,
	IDC_TXT_PLUGIN_KEY_EDIT_HELP_INFO2,


    IDD_PLUGIN_KEY_ADD,
	IDC_TXT_PLUGIN_KEY_ADD_TITLE,
	IDC_TXT_PLUGIN_KEY_ADD_CAID,
	IDC_TXT_PLUGIN_KEY_ADD_PROVIDER,
	IDC_TXT_PLUGIN_KEY_ADD_TYPE,
	IDC_TXT_PLUGIN_KEY_ADD_INDEX,
	IDC_TXT_PLUGIN_KEY_ADD_KEY_DATA,
	IDC_EDIT_PLUGIN_KEY_ADD_CAID_CONTENT,
	IDC_EDIT_PLUGIN_KEY_ADD_PROVIDER_CONTENT,
	IDC_BTN_PLUGIN_KEY_ADD_TYPE_CONTENT,
	IDC_EDIT_PLUGIN_KEY_ADD_INDEX_CONTENT,
	IDC_EDIT_PLUGIN_KEY_ADD_KEY_DATA_CONTENT,
//	IDC_EDIT_PLUGIN_KEY_ADD_KEY_DATA_CONTENT1,
	IDC_TXT_PLUGIN_KEY_ADD_HELP_INFO1,
	IDC_TXT_PLUGIN_KEY_ADD_HELP_INFO2,


    MCAS_IDD_NUM,

}MCAS_RES_CTRL_ID;


extern const YWGUI_DlgTemplate_T g_template_mcasmain;
extern const YWGUI_DlgTemplate_T g_template_mcascardinfo;
extern const YWGUI_DlgTemplate_T g_template_mcaskeyeditorentry;


//extern const YWGUI_DlgTemplate_T g_template_pluginmain;
extern const YWGUI_DlgTemplate_T g_template_pluginkeyinfo;
extern const YWGUI_DlgTemplate_T g_template_pluginkeyedit;
extern const YWGUI_DlgTemplate_T g_template_pluginkeyadd;
extern const YWGUI_DlgTemplate_T g_template_mcasoption;
extern const YWGUI_DlgTemplate_T g_template_mcassysinfo;


#endif

