version: '3'
services:
  builder:
    environment:
      - PLUGINROOT=/root/spark
      - PLUGINAPP=/root/spark/app
      - PLUGIN_TARGET=iptv
    build: .
    volumes:
      - ./release:/app/output

    command: /root/spark/docker-entrypoint.sh