#include "ywgui_ext.h"
#include "res_layout.h"
#include "tuner_layout.h"



#define _TXT_START_X_ 100
#define _TXT_START_Y_ 50
#define _TXT_W_ 300
#define _EDIT_W_ (1220-_TXT_START_X_*2-_TXT_W_)


#define DOT_WIDTH 12
#define SERVERNAME_WIDTH 68
#define TXT_L_R_SERVNAMEW ((_EDIT_W_-(4*SERVERNAME_WIDTH)-(3*DOT_WIDTH))/2)

static YWGUI_LRCombobox_AddData_T NetClntDown4LRCBAddData =
{
    //Edit的外形
    &g_tLRCBEditShapeInfo,

    //List的位置
    0, 52, _EDIT_W_, (52*4+78),

    //List的外形
    &g_tPopDlgHaveHeadShapeInfo,
    &g_tLRCBListAddData
};

static YWGUI_LRCombobox_AddData_T NetClntDown2LRCBAddData =
{
    //Edit的外形
    &g_tLRCBEditShapeInfo,

    //List的位置
    0, 52, _EDIT_W_, (52*2+78),

    //List的外形
    &g_tPopDlgHaveHeadShapeInfo,
    &g_tLRCBListAddData
};



static YWGUI_CtrlTemplate_T g_ctrl_template_tuner_demo[] =
{
    /*title text*/
    {(const S8*)YWGUI_CTRL_STATIC,YWGUI_WS_VISIBLE|YWGUI_SS_CENTER|YWGUI_SS_VCENTER,YWGUI_WS_EX_NONE |YWGUI_WS_EX_TRANSPARENT|YWGUI_WS_EX_TITLECTRL,
      (YWPUBLIC_COMM_DLG_W-400)/2, 36, 400, CTRL_COMMON_HIGH,
      IDC_TXT_TUNER_DEMO_TITLE, STR_EMPTY,0,0},

    //tuner
    {(const S8*)YWGUI_CTRL_STATIC, YWGUI_WS_VISIBLE|YWGUI_SS_LEFT|YWGUI_SS_VCENTER, YWGUI_WS_EX_TRANSPARENT,
       _TXT_START_X_, _TXT_START_Y_, _TXT_W_, CTRL_COMMON_HIGH, IDC_TXT_TUNER_DEMO_SAT_L, STR_EMPTY, 0, &g_tTxtBlackWhiteShapeInfo},
    /*
    {(const S8*)YWGUI_CTRL_BUTTON, YWGUI_WS_VISIBLE|YWGUI_BS_CENTER|YWGUI_BS_VCENTER, YWGUI_WS_EX_NONE |YWGUI_WS_EX_NOTIFY,
        (_TXT_START_X_+_TXT_W_), _TXT_START_Y_+CTRL_COMMON_HIGH*0, _EDIT_W_, CTRL_COMMON_HIGH,
        IDC_TXT_TUNER_DEMO_SAT_R, 0, 0, &g_tButtonShapeInfo},
        */
    {(const S8*)YWGUI_CTRL_LRCOMBOBOX, YWGUI_WS_VISIBLE|YWGUI_LRCBS_AUTOSCROLL|YWGUI_LRCBS_CENTER|YWGUI_LRCBS_VCENTER|YWGUI_LRCBS_EXITKEYHIDELIST,YWGUI_WS_EX_NOTIFY,
       _TXT_START_X_+_TXT_W_, _TXT_START_Y_+CTRL_COMMON_HIGH*0, _EDIT_W_, CTRL_COMMON_HIGH,
       IDC_TXT_TUNER_DEMO_SAT_R, 0, (DWORD)&NetClntDown2LRCBAddData, 0},
        

    //lnb
    {(const S8*)YWGUI_CTRL_STATIC, YWGUI_WS_VISIBLE|YWGUI_SS_LEFT|YWGUI_SS_VCENTER, YWGUI_WS_EX_TRANSPARENT,
       _TXT_START_X_, _TXT_START_Y_+CTRL_COMMON_HIGH*1, _TXT_W_, CTRL_COMMON_HIGH, IDC_TXT_TUNER_DEMO_LNB_L, STR_EMPTY, 0, &g_tTxtBlackWhiteShapeInfo},
    {(const S8*)YWGUI_CTRL_BUTTON, YWGUI_WS_VISIBLE|YWGUI_BS_CENTER|YWGUI_BS_VCENTER, YWGUI_WS_EX_NONE |YWGUI_WS_EX_NOTIFY,
        (_TXT_START_X_+_TXT_W_), _TXT_START_Y_+CTRL_COMMON_HIGH*1, _EDIT_W_, CTRL_COMMON_HIGH,
        IDC_TXT_TUNER_DEMO_LNB_R, 0, 0, &g_tButtonShapeInfo},


    //22k
    {(const S8*)YWGUI_CTRL_STATIC, YWGUI_WS_VISIBLE|YWGUI_SS_LEFT|YWGUI_SS_VCENTER, YWGUI_WS_EX_TRANSPARENT,
       _TXT_START_X_, _TXT_START_Y_+CTRL_COMMON_HIGH*2, _TXT_W_, CTRL_COMMON_HIGH, IDC_TXT_TUNER_DEMO_22k_L, STR_EMPTY, 0, &g_tTxtBlackWhiteShapeInfo},
    {(const S8*)YWGUI_CTRL_LRCOMBOBOX, YWGUI_WS_VISIBLE|YWGUI_LRCBS_AUTOSCROLL|YWGUI_LRCBS_CENTER|YWGUI_LRCBS_VCENTER|YWGUI_LRCBS_EXITKEYHIDELIST,YWGUI_WS_EX_NOTIFY,
       _TXT_START_X_+_TXT_W_, _TXT_START_Y_+CTRL_COMMON_HIGH*2, _EDIT_W_, CTRL_COMMON_HIGH,
       IDC_TXT_TUNER_DEMO_22k_R, 0, (DWORD)&NetClntDown2LRCBAddData, 0},

    //disqc
    {(const S8*)YWGUI_CTRL_STATIC, YWGUI_WS_VISIBLE|YWGUI_SS_LEFT|YWGUI_SS_VCENTER, YWGUI_WS_EX_TRANSPARENT,
       _TXT_START_X_, _TXT_START_Y_+CTRL_COMMON_HIGH*3, _TXT_W_, CTRL_COMMON_HIGH, IDC_TXT_TUNER_DEMO_DISEQC_L, STR_EMPTY, 0, &g_tTxtBlackWhiteShapeInfo},
    {(const S8*)YWGUI_CTRL_LRCOMBOBOX, YWGUI_WS_VISIBLE|YWGUI_LRCBS_AUTOSCROLL|YWGUI_LRCBS_CENTER|YWGUI_LRCBS_VCENTER|YWGUI_LRCBS_EXITKEYHIDELIST,YWGUI_WS_EX_NOTIFY,
       _TXT_START_X_+_TXT_W_, _TXT_START_Y_+CTRL_COMMON_HIGH*3, _EDIT_W_, CTRL_COMMON_HIGH,
       IDC_TXT_TUNER_DEMO_DISEQC_R, 0, (DWORD)&NetClntDown4LRCBAddData, 0},

    //freq
    {(const S8*)YWGUI_CTRL_STATIC, YWGUI_WS_VISIBLE|YWGUI_SS_LEFT|YWGUI_SS_VCENTER, YWGUI_WS_EX_TRANSPARENT,
       _TXT_START_X_, _TXT_START_Y_+CTRL_COMMON_HIGH*4, _TXT_W_, CTRL_COMMON_HIGH, IDC_TXT_TUNER_DEMO_FREQ_L, STR_EMPTY, 0, &g_tTxtBlackWhiteShapeInfo},
    {(const S8*)YWGUI_CTRL_BUTTON, YWGUI_WS_VISIBLE|YWGUI_BS_CENTER|YWGUI_BS_VCENTER, YWGUI_WS_EX_NONE |YWGUI_WS_EX_NOTIFY,
        (_TXT_START_X_+_TXT_W_), _TXT_START_Y_+CTRL_COMMON_HIGH*4, _EDIT_W_, CTRL_COMMON_HIGH,
        IDC_TXT_TUNER_DEMO_FREQ_R, 0, 0, &g_tButtonShapeInfo},


    //symbrate
    {(const S8*)YWGUI_CTRL_STATIC, YWGUI_WS_VISIBLE|YWGUI_SS_LEFT|YWGUI_SS_VCENTER, YWGUI_WS_EX_TRANSPARENT,
       _TXT_START_X_, _TXT_START_Y_+CTRL_COMMON_HIGH*5, _TXT_W_, CTRL_COMMON_HIGH, IDC_TXT_TUNER_DEMO_SYMRATE_L, STR_EMPTY, 0, &g_tTxtBlackWhiteShapeInfo},
    {(const S8*)YWGUI_CTRL_BUTTON, YWGUI_WS_VISIBLE|YWGUI_BS_CENTER|YWGUI_BS_VCENTER, YWGUI_WS_EX_NONE |YWGUI_WS_EX_NOTIFY,
        (_TXT_START_X_+_TXT_W_), _TXT_START_Y_+CTRL_COMMON_HIGH*5, _EDIT_W_, CTRL_COMMON_HIGH,
        IDC_TXT_TUNER_DEMO_SYMRATE_R, 0, 0, &g_tButtonShapeInfo},

    //pol
    {(const S8*)YWGUI_CTRL_STATIC, YWGUI_WS_VISIBLE|YWGUI_SS_LEFT|YWGUI_SS_VCENTER, YWGUI_WS_EX_TRANSPARENT,
       _TXT_START_X_, _TXT_START_Y_+CTRL_COMMON_HIGH*6, _TXT_W_, CTRL_COMMON_HIGH, IDC_TXT_TUNER_DEMO_POL_L, STR_EMPTY, 0, &g_tTxtBlackWhiteShapeInfo},
    {(const S8*)YWGUI_CTRL_LRCOMBOBOX, YWGUI_WS_VISIBLE|YWGUI_LRCBS_AUTOSCROLL|YWGUI_LRCBS_CENTER|YWGUI_LRCBS_VCENTER|YWGUI_LRCBS_EXITKEYHIDELIST,YWGUI_WS_EX_NOTIFY,
       _TXT_START_X_+_TXT_W_, _TXT_START_Y_+CTRL_COMMON_HIGH*6, _EDIT_W_, CTRL_COMMON_HIGH,
       IDC_TXT_TUNER_DEMO_POL_R, 0, (DWORD)&NetClntDown2LRCBAddData, 0},



    {(const S8*)YWGUI_CTRL_PICTURE,YWGUI_WS_VISIBLE,YWGUI_WS_EX_TRANSPARENT,
      HOTKEY_START_X, HOTKEY_START_Y,46,46,
      IDC_TXT_TUNER_DEMO_RED_L,STR_EMPTY,(DWORD)&g_aGraphCellArray[YWCELL_RED], 0},
    {(const S8*)YWGUI_CTRL_STATIC, YWGUI_WS_VISIBLE|YWGUI_SS_VCENTER|YWGUI_SS_LEFT, YWGUI_WS_EX_TRANSPARENT,
       HOTKEY_START_X+50, HOTKEY_START_Y, 100, CTRL_COMMON_HIGH, IDC_TXT_TUNER_DEMO_RED_R, STR_EMPTY, 0, &g_tTxtBlackWhiteShapeInfo},
};


const YWGUI_DlgTemplate_T g_template_tuner_demo =
{
    IDD_TUNER_DEMO_ENTRY,
    YWGUI_WS_VISIBLE,
    YWGUI_WS_EX_NONE,
    (YWPUBLIC_OSD_W - YWPUBLIC_COMM_DLG_W)/2,
    (YWPUBLIC_OSD_H - YWPUBLIC_COMM_DLG_H)/2,
    YWPUBLIC_COMM_DLG_W,
    YWPUBLIC_COMM_DLG_H,
    -1,
    YWGUI_ARRAY_SIZE(g_ctrl_template_tuner_demo),
    g_ctrl_template_tuner_demo,
    0,
    NULL
};










