#ifndef _TUNER_LAYOUT_H
#define _TUNER_LAYOUT_H

/*the ID of window*/
typedef enum
{
	//id
	IDD_TUNER_DEMO_ENTRY = 0x800,
	IDC_TXT_TUNER_DEMO_TITLE,
	IDC_TXT_TUNER_DEMO_SAT_L,
	IDC_TXT_TUNER_DEMO_LNB_L,
	IDC_TXT_TUNER_DEMO_22k_L,
	IDC_TXT_TUNER_DEMO_DISEQC_L,
	IDC_TXT_TUNER_DEMO_FREQ_L,
	IDC_TXT_TUNER_DEMO_SYMRATE_L,
	IDC_TXT_TUNER_DEMO_POL_L,
	IDC_TXT_TUNER_DEMO_SAT_R,
	IDC_TXT_TUNER_DEMO_LNB_R,
	IDC_TXT_TUNER_DEMO_22k_R,
	IDC_TXT_TUNER_DEMO_DISEQC_R,
	IDC_TXT_TUNER_DEMO_FREQ_R,
	IDC_TXT_TUNER_DEMO_SYMRATE_R,
	IDC_TXT_TUNER_DEMO_POL_R,
	IDC_TXT_TUNER_DEMO_RED_L,
	IDC_TXT_TUNER_DEMO_RED_R,
    TUNER_DEMO_IDD_NUM,

}TUNER_DEMO_RES_CTRL_ID;

extern const YWGUI_DlgTemplate_T g_template_tuner_demo;


#endif





