


#ifndef _IPTV_LAYOUT_H
#define _IPTV_LAYOUT_H




enum
{
	YWCELL_PLAYER_NOR_PLAY,
    YWCELL_PLAYER_NOR_STOP,
    YWCELL_PLAYER_NOR_PAUSE,
    YWCELL_PLAYER_CUR_PLAY,
    YWCELL_PLAYER_CUR_STOP,
    YWCELL_PLAYER_CUR_PAUSE,
    YWCELL_PLAYER_HIDE_PLAY,
    YWCELL_PLAYER_HIDE_STOP,
    YWCELL_PLAYER_HIDE_PAUSE,
    YWCELL_IPTV_ICON,
    YWCELL_HELP_LINE,
    YWCELL_PROCESS_BLACK,
    YWCELL_PROCESS_YELLOW,
    YWCELL_PROCESS_BK_L,
    YWCELL_PROCESS_BK_R,
    YWCELL_POP_BUTTON_CUR,
    YWCELL_POP_BUTTON_NOR,

	YWCELL_VOL_CUR,
	YWCELL_VOL_L,
	YWCELL_VOL_M,
	YWCELL_VOL_R,

	YWCELL_WAIT_BAR,
    YWCELL_WAIT_BAR_BK,

    IPTVCELL_NUM,
};


/*the ID of window*/
typedef enum
{
	//net client config
	IDD_IPTV = 0x800,
	IDC_PIC_IPTV_ICON,
	IDC_TXT_IPTV_PAGE,
	IDC_TXT_IPTV_SMALLWIN,
	IDC_PIC_IPTV_SMALL_PLAY,
    IDC_PIC_IPTV_SMALL_STOP,
    IDC_PIC_IPTV_SMALL_PAUSE,
    IDC_PROGRESS_IPTV_SMALL,
    IDC_TXT_IPTV_INFO_TITLE,
    IDC_TXT_IPTV_INFO_DETAIL,

	IDC_LT_IPTV,

	IDC_TXT_IPTV_BAR,

	IDC_PIC_IPTV_ADD_IPTV,
	IDC_TXT_IPTV_ADD_IPTV,
	IDC_PIC_IPTV_EDIT_IPTV,
	IDC_TXT_IPTV_EDIT_IPTV,
	IDC_PIC_IPTV_FULL_SCREEN,
	IDC_TXT_IPTV_FULL_SCREEN,


	//IpTv Edit
	IDD_IPTV_ADD,
	IDC_TXT_IPTV_ADD_TITLE,

	IDC_CTN_IPTV_ADD_TV_TITLE,
	IDC_TXT_IPTV_ADD_TV_TITLE_L,
	IDC_TXT_IPTV_ADD_TV_TITLE_R,
	IDC_CTN_IPTV_ADD_TV_URL,
	IDC_TXT_IPTV_ADD_TV_URL_L,
	IDC_TXT_IPTV_ADD_TV_URL_R,
	IDC_CTN_IPTV_ADD_TV_DESCRIPTION,
	IDC_TXT_IPTV_ADD_TV_DESCRIPTION_L,
	IDC_TXT_IPTV_ADD_TV_DESCRIPTION_R,
	IDC_CTN_IPTV_ADD_MEDIA_TYPE,
	IDC_TXT_IPTV_ADD_MEDIA_TYPE_L,
	IDC_LRC_IPTV_ADD_MEDIA_TYPE_R,
	IDC_BTN_IPTV_ADD,
	IDC_BTN_IPTV_EXIT,



	//IpTv Edit
	IDD_IPTV_EDIT,
	IDC_BTN_IPTV_DELETE,


	//IpTv Play window
	IDD_IPTV_PLAY,
	IDC_TXT_IPTV_VOLUME_BK,
	IDC_PROGRRESS_IPTV_VOLUME,
	IDC_PIC_IPTV_BIG_PLAY,
	IDC_PIC_IPTV_BIG_STOP,
	IDC_PIC_IPTV_BIG_PAUSE,
	IDC_PROGRESS_IPTV_BIG,

	//wait wnd
	IDD_WAIT,
	IDC_PIC_WAIT,
	
    IPTV_IDD_NUM,

}IPTV_RES_CTRL_ID;

extern YWGUI_GraphCell_T g_aIpTvGraphCellArray[IPTVCELL_NUM];


extern const YWGUI_DlgTemplate_T gTemplateAmikoMainWnd;



void APP_IpTVResLoad(void);
void APP_IpTVResUnLoad(void);


extern const YWGUI_DlgTemplate_T g_template_webtv;
extern const YWGUI_DlgTemplate_T g_template_webtvadd;
extern const YWGUI_DlgTemplate_T g_template_webtvedit;
extern const YWGUI_DlgTemplate_T g_template_webTvPlayWnd;
extern const YWGUI_DlgTemplate_T gTemplateWaitWnd;



void APP_IpTVResLoad(void);
void APP_IpTVResUnLoad(void);


#endif




