
#ifndef _GUI_H_20080416_
#define  _GUI_H_20080416_


typedef enum
{
    YWGUI_SCANCODE_MENU=0xf005,//YWGUI_SCANCODE_DOWN+1,
    YWGUI_SCANCODE_PGUP = 0xf008,
    YWGUI_SCANCODE_PGDN = 0xf007,

    YWGUI_SCANCODE_RED =0xf101,//63,//88,
    YWGUI_SCANCODE_GREEN = 0xf102,//64,//113,
    YWGUI_SCANCODE_YELLOW = 0xf103,//65,//114,
    YWGUI_SCANCODE_BLUE = 0xf104,//66,//115,

    YWGUI_SCANCODE_TIMER = 118,
    YWGUI_SCANCODE_TIMESHIFT = 0x3d,
//    YWGUI_SCANCODE_PIP = 0x6c,   //same to YWGUI_SCANCODE_DOWN
    YWGUI_SCANCODE_TVSAT = 0xf10d,
    YWGUI_SCANCODE_TVRADIO = 0xf115,
    YWGUI_SCANCODE_RECALL = 0xf109,//F9
    YWGUI_SCANCODE_FIND = 0xf107,//F7
    YWGUI_SCANCODE_RECORD = 0xf118,
    YWGUI_SCANCODE_FAV = 0xf108,//F8
    YWGUI_SCANCODE_FOLDER = 0xf10a,//F10
    YWGUI_SCANCODE_STOP = 0xf00a, //break
    YWGUI_SCANCODE_PLAY = 0xf050,
    YWGUI_SCANCODE_PREV = 0xf05b,
    YWGUI_SCANCODE_NEXT = 0xf05c,
    YWGUI_SCANCODE_BACK_SLOW = 0x3b,
    YWGUI_SCANCODE_FORWARD_SLOW = 0x22,
    YWGUI_SCANCODE_WHITE = 0x2f,
    YWGUI_SCANCODE_USB = 0xf201,


    YWGUI_SCANCODE_POWER = 134,
    YWGUI_SCANCODE_MUTE = 0xf04e,
    YWGUI_SCANCODE_VOL_DOWN = 0xf04c,//44,
    YWGUI_SCANCODE_VOL_UP = 0xf04d,//45,
    YWGUI_SCANCODE_GUIDE = 0xf106,//F6
    YWGUI_SCANCODE_VIDEO_FORMAT = 0x63,
    YWGUI_SCANCODE_INFO = 0xf105, //F5
    YWGUI_SCANCODE_PAUSE = 0x62,
    YWGUI_SCANCODE_RECEDE = 0x6d,
    YWGUI_SCANCODE_FORWARD = 0x6e,
    YWGUI_SCANCODE_SAT = 0xf501,


    YWGUI_SCANCODE_PLAY_MODE = 0x2f,
    YWGUI_SCANCODE_PORTAL = 0xf210,


    YWGUI_SCANCODE_DUMMY_KEY = 255,       /*for inform host window, when exit from window*/


}YWPUBLIC_Scancode_T;



/*MSG*/
enum
{
    YWPUBLIC_MSG_USER_CHANGE = (YWGUI_MSG_USER+1),
    YWPUBLIC_MSG_RENAME,
    YWPUBLIC_MSG_CREAT_MENU,
    YWPUBLIC_MSG_DESTROY_MENU,
    YWPUBLIC_MSG_UPDATE_EN2KERNEL,
	YWPUBLIC_MSG_UPDATE_EN2FS,
	YWPUBLIC_MSG_CONFIRM_INFO,
	YWPUBLIC_MSG_FRESH_INFO,
	YWPUBLIC_MSG_UPDATE_EN2REMOTE,
	YWPUBLIC_MSG_IPTV_LIST_REFRESH,
	YWPUBLIC_MSG_INIT_FAIL_INFO,
	YWPUBLIC_MSG_UPDATE_UBOOT,

	YWPUBLIC_MSG_WEBTV_LIST_REFRESH,
	YWPUBLIC_MSG_END_OF_FILE,
	YWPUBLIC_MSG_WEBTV_PLAY,
	YWPUBLIC_MSG_WEBTV_EXIT_BIG,
	YWPUBLIC_MSG_START_WAIT,

	//amiko tv msg
	YWPUBLIC_MSG_AMIKOTV_UPDATE,
	YWPUBLIC_MSG_ENTER_MAINWIN,
	YWPUBLIC_MSG_KTV_LOGIN,
	YWPUBLIC_MSG_KTV_LOGOUT,
	YWPUBLIC_MSG_KTV_GET_CHANNEL_LIST,
	YWPUBLIC_MSG_KTV_GET_CHANNEL_POSTER,
	YWPUBLIC_MSG_KTV_GET_EPG,
	YWPUBLIC_MSG_KTV_GET_EPG_NEXT,
	YWPUBLIC_MSG_KTV_GET_URL,
	YWPUBLIC_MSG_KTV_GET_VOD_GENRES,
	YWPUBLIC_MSG_KTV_GET_VOD_LIST,
	YWPUBLIC_EVT_GET_VOD_POSTER,
	YWPUBLIC_MSG_KTV_GET_VOD_INFO,
	YWPUBLIC_MSG_KTV_GET_VOD_URL,
	YWPUBLIC_MSG_KTV_GET_VOD_INFO_POSTER,
	YWPUBLIC_MSG_KTV_EXIT_OK_LIST,
	YWPUBLIC_MSG_KTV_CHANGE_PROG,
	YWPUBLIC_MSG_KTV_PLAY,
	YWPUBLIC_MSG_KTV_UPDATE_EPG,
	YWPUBLIC_MSG_KTV_EXIT_PLAY,
	YWPUBLIC_MSG_KTV_UPDATE_VOD,
	YWPUBLIC_MSG_KTV_EXIT_POP,
	YWPUBLIC_MSG_END_WAIT,
	YWPUBLIC_MSG_EXIT_WAIT,
	YWPUBLIC_MSG_AMIKOTV_STARTCALL_API,
	YWPUBLIC_MSG_KTV_LOGIN_AND_GETCHNLIST,

	YWPUBLIC_MSG_OSCAM_DOWNLOADFILE,
	YWPUBLIC_MSG_OSCAM4SPARK_RESTART,

	YWPUBLIC_MSG_OSCAM4SPARK_DISPCONECTINFO,
	YWPUBLIC_MSG_OSCAM4SPARK_ENCRYPT,

	YWPUBLIC_MSG_SAMI_DOWNLOAD,

};


#define YWPUBLIC_TIMER                  1

enum
{
	TIMER_INFOBAR = YWPUBLIC_TIMER,
	TIMER_WEBTV_INFO,
	TIMER_WEBTV_PLAY_PROGRESS,
	TIMER_WEBTV_VOLUME,
	TIMER_WEBTV_REFRESH,

	TIMER_KTV_VOLUME,
    TIMER_KTV_REFRESH,
    TIMER_KTV_BANNER,
    TIMER_KTV_REFRESH_EPG_NOW,
    TIMER_KTV_REFRESH_TIME,
    TIMER_KTV_INPUT,
    TIMER_KTV_GET_EPG,

	TIMER_YOUTUBE_PLAY,

};


void APP_ModifyFontSize(S8 *fontatrr);
#endif


