


#ifndef _CAMCFG_LAYOUT_H
#define _CAMCFG_LAYOUT_H

/*the ID of window*/
typedef enum
{
	//net client config
	IDD_NET_CLIENT_CONFIG = 0x300,
	IDC_TXT_NET_CFG_TITLE,
	IDC_PIC_NET_CFG_OSCAM,
	IDC_PIC_NET_CFG_CCCAMD,
	IDC_PIC_NET_CFG_MGCFG,
	IDC_BTN_NET_CFG_OSCAM,
	IDC_BTN_NET_CFG_MGCFG,
	IDC_BTN_NET_CFG_CCCAMCFG,
	IDC_BTN_NET_CFG_INFOR,
	IDC_PIC_NET_CFG_RED,
	IDC_TXT_NET_CFG_START_STORP,


	//mg cfg
	IDD_MG_CONFIG,
	IDC_TXT_MG_CONFIG_TITLE,
	IDC_BTN_MG_CONFIG_NEWCAMD,
	IDC_BTN_MG_CONFIG_CCCAMD,

	//net client cfg edit
	IDD_NET_CLIENT_CONFIG_EDIT,
	IDC_TXT_NET_CFG_EDIT_TITLE,
	IDC_TXT_NET_CFG_EDIT_INDEX,
	IDC_LRC_NET_CFG_EDIT_INDEX,
	IDC_TXT_NET_CFG_EDIT_SERV_NAME,
/*	IDC_TXT_NET_CFG_EDIT_SERV_NAMEL,
	IDC_TXT_NET_CFG_EDIT_SERV_DOT1,
	IDC_TXT_NET_CFG_EDIT_SERV_DOT2,
	IDC_TXT_NET_CFG_EDIT_SERV_DOT3,
	IDC_EDIT_NET_CFG_EDIT_SERV_NAME1,
	IDC_EDIT_NET_CFG_EDIT_SERV_NAME2,
	IDC_EDIT_NET_CFG_EDIT_SERV_NAME3,
	IDC_EDIT_NET_CFG_EDIT_SERV_NAME4,
	IDC_TXT_NET_CFG_EDIT_SERV_NAMER,
	IDC_CTN_NET_CFG_EDIT_SERV_NAME,*/
	IDC_BTN_NET_CFG_EDIT_SERV_NAME,
	IDC_TXT_NET_CFG_EDIT_SERVICE_PORT,
	IDC_EDIT_NET_CFG_EDIT_SERVICE_PORT,
	IDC_TXT_NET_CFG_EDIT_SERVICE_PORT_END,
	IDC_EDIT_NET_CFG_EDIT_SERVICE_PORT_END,
	IDC_TXT_NET_CFG_EDIT_USER_NAME,
	IDC_BTN_NET_CFG_EDIT_USER_NAME,
	IDC_TXT_NET_CFG_EDIT_PASSWORD,
	IDC_BTN_NET_CFG_EDIT_PASSWORD,
	IDC_TXT_NET_CFG_EDIT_DES_KEY,
	IDC_EDIT_NET_CFG_EDIT_DES_KEY,
	IDC_TXT_NET_CFG_EDIT_PROTOCOL,
	IDC_LRC_NET_CFG_EDIT_PROTOCOL,
	IDC_TXT_NET_CFG_EDIT_HELP,
	IDC_PIC_NET_CFG_EDIT_RED,
	IDC_TXT_NET_CFG_EDIT_ADD,
	IDC_PIC_NET_CFG_EDIT_GREEN,
	IDC_TXT_NET_CFG_EDIT_DELETE,
	IDC_PIC_NET_CFG_EDIT_YELLOW,
	IDC_TXT_NET_CFG_EDIT_PING,
	IDC_PIC_NET_CFG_EDIT_BLUE,
	IDC_TXT_NET_CFG_EDIT_F,
	IDC_TXT_NET_CFG_EDIT_AB,

	//net client cfg  general info
	IDD_NET_CLIENT_CONFIG_ACTIVE_INFO,
	IDC_TXT_NET_CFG_ACTIVE_STATUS,
	IDC_LT_NET_CFG_ACTIVE_STATUS,

	//pop save info

	//ping info
	IDD_NET_CLIENT_CONFIG_PING_INFO,
	IDC_TXT_NET_CFG_PING_INFO,

	//net client cfg ping
	IDD_NET_CLIENT_CONFIG_PING,
	IDC_TXT_NET_CFG_PING_TITLE,
	IDC_TXT_NET_CFG_PING_MODE,
	IDC_LRC_NET_CFG_PING_MODE,
	IDC_TXT_NET_CFG_PING_TIMEOUT,
	IDC_LRC_NET_CFG_PING_TIMEOUT,
	IDC_TXT_NET_CFG_PING_PACKET,
	IDC_LRC_NET_CFG_PING_PACKET,
	IDC_TXT_NET_CFG_PING_TARGET,
	IDC_LRC_NET_CFG_PING_TARGET,
	IDC_TXT_NET_CFG_PING_RUN,
	IDC_BTN_NET_CFG_PING_RUN,

	//information
	IDD_NET_CFG_INFOR,
	IDC_TXT_NET_CFG_INFOR_TITLE,
	IDC_TXT_NET_CFG_INFOR_VISITUS_L,
	IDC_TXT_NET_CFG_INFOR_VISITUS_R,
	IDC_TXT_NET_CFG_INFOR_VISITUS_R1,
	IDC_TXT_NET_CFG_INFOR_VISITUS_R2,
	IDC_TXT_NET_CFG_INFOR_VISITUS_R3,
	IDC_TXT_NET_CFG_INFOR_VISITUS_R4,


    CAMCFG_IDD_NUM,

}CAMCFG_RES_CTRL_ID;



extern const YWGUI_DlgTemplate_T g_template_netclntcfg;
extern const YWGUI_DlgTemplate_T g_template_mgcfg;
extern const YWGUI_DlgTemplate_T g_template_activeinfocfg;
extern const YWGUI_DlgTemplate_T g_template_pinginfocfg;
extern const YWGUI_DlgTemplate_T g_template_netclntcfgedit;
extern const YWGUI_DlgTemplate_T g_template_netclntcfgping;
extern const YWGUI_DlgTemplate_T g_template_netcfginfo;

#endif




